### ISSUE TITLE
problem with my bot

### ISSUE THREAD

**Issue by sanshiro** [stacktodo/stacktodo_js_api#1]
hello guys, i just change the name of the invite channel and my bot stop working, is off line now. I delete the channel, disable the bot account, then enable again and invite it to a new channel, nothing is working :(

team hittco.slack.com

**Comment by michabbb** [comment]
seems like this project is dead.... :cry:

**Comment by TJohnson93** [comment]
That would explain why I can't invite the bot!

**Comment by dimante** [comment]
I cannot invite the bot either... Noone from support is responding...  Odd.

**Comment by dimante** [comment]
Does that mean this is fixed?

**Comment by michabbb** [comment]
@dimante *LOL* someone closes an issue that is 1,5 years old without any comment and you really ask, if its fixed ? i don´t know which of these facts are more funny ;-)))))

**Comment by dimante** [comment]
Why close it then? The whole GitHub should be taken offline.  Odd way to go
about this...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

*This email may contain information that is confidential or attorney-client
privileged and may constitute inside information. The contents of this
email are intended only for the recipient(s) listed above. If you are not
the intended recipient, you are directed not to read, disclose, distribute
or otherwise use this transmission. If you have received this email in
error, please notify the sender immediately and delete the transmission.
Delivery of this message is not intended to waive any applicable
privileges.*

On Mon, Jul 17, 2017 at 3:45 PM, Michael Bladowski <notifications@github.com

**Comment by michabbb** [comment]
as you noticed, this project become useless the same as your "confidential spam text" you send to all of your recipients which costs the internet TB of useless traffic, but anyway.... if you still need a readonly channel, there are [some projects](https://github.com/jclg/php-slack-bot) available that help you to build a simple bot which listens to all messages you can easily delete if it matches to your filters.....
